### ISSUE TITLE
[RMP] Larger than GPU memory embedding tables

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#107]
# Merlin-models(Data Scientist)
GPU Embedding cache and parameter server integration

# NVTabular(Data Scientist)

# Merlin-systems(Product Engineer)
GPU Embedding cache and parameter server integration

# Merlin-orchestration(Infra Engineer)

# Examples and Docs(Everyone)

Aha! Link: https://nvaiinfa.aha.io/features/MERLIN-826

**Comment by EvenOldridge** [comment]
Duplicate of https://github.com/NVIDIA-Merlin/models/issues/415

**Comment by karlhigley** [comment]
Am I wrong in thinking we want all the RMP issues on the Merlin repo?
