### ISSUE TITLE
[BUG] Merlin io - ModuleNotFoundError: No module named 'cudf._version'

### ISSUE THREAD

**Issue by vivpra89** [NVIDIA-Merlin/Merlin#1076]
<img width="477" alt="image" src="https://github.com/NVIDIA-Merlin/Merlin/assets/7903777/196d0788-a0cb-4e8a-9d16-552a79dc5ee3">

This worked till yesterday and started throwing error today. any fix to this. NVTABULAR uses merlin and it doesnt work due to this. any way out.

**Comment by rnyak** [comment]
@vivpra89 can I ask what did you change from yesterday to today? docker image? the GPU machine? the driver?

**Comment by rnyak** [comment]
@vivpra89 I am closing this issue due to low activity. you can reopen it if you need to.
