### ISSUE TITLE
[RMP] Filter out previously interacted items

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#108]
# Merlin-models(Data Scientist)
Integrated filtering?

# NVTabular(Data Scientist)

# Merlin-systems(Product Engineer)
Operators for applying filters during serving/batch

# Merlin-orchestration(Infra Engineer)
Build Bloom filters

# Examples and Docs(Everyone)

Aha! Link: https://nvaiinfa.aha.io/features/MERLIN-825

**Comment by karlhigley** [comment]
We should probably consider this part of #102, since it doesn't matter if we have an ensemble API if we don't also have the essential building blocks to put in an ensemble

**Comment by EvenOldridge** [comment]
Duplicate of #703
