### ISSUE TITLE
[RMP] Feature Store updating

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#109]
# Merlin-models(Data Scientist)

# NVTabular(Data Scientist)
Streaming based NVT ops

# Merlin-systems(Product Engineer)
Feature store access

# Merlin-orchestration(Infra Engineer)
Feature store update mechanism

# Examples and Docs(Everyone)

Aha! Link: https://nvaiinfa.aha.io/features/MERLIN-824

**Comment by karlhigley** [comment]
This one is probably a farther future issue, once we start tackling MLops more seriously

**Comment by nv-alaiacano** [comment]
Closing this. If the subject comes up again, we can re-assess.
