### ISSUE TITLE
[QST] What is the best way of handling string UUIDs in Merlin?

### ISSUE THREAD

**Issue by BlakeB415** [NVIDIA-Merlin/Merlin#1091]
### Discussed in https://github.com/NVIDIA-Merlin/Merlin/discussions/1089

<div type='discussions-op-text'>

<sup>Originally posted by **BlakeB415** December 22, 2023</sup>
What would be the best way of going about this? I would rather not maintain a separate UUID to Int mapping table.

My original idea was to either Hash or Categorify the UUID values for training, then have the ``user_id_raw`` and ``item_id_raw`` string values be returned from the Feast store during inference so that my application can get the raw UUIDs.

However, Merlin does not support this paradigm as I get type errors during inference.
</div>

**Comment by BlakeB415** [comment]
Hi, it's been a week. Does anyone know how to deal with this? Thank you.

**Comment by rnyak** [comment]
@BlakeB415 please share your error message and also a toy example for us to repro your issue.
