### ISSUE TITLE
[RMP] Container size reduction

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#112]
- https://github.com/NVIDIA-Merlin/Merlin/issues/90
- https://github.com/NVIDIA-Merlin/Merlin/pull/100
- 

- [x] Reporting size per component
- [x] - Trying Tritonserver smaller base images: tf/pyt
- [x] - (NO NEED) Rapids from internal image (Note: This is not preferred. This may hamper customers who build their own conatiners)
- [x] - (NO NEED) HugeCTR dependencies as optional (Needs product approval)

**Comment by albert17** [comment]
Done:
- Minimized System Packages
- Minimized Python Packages
- Minimized Dependencies

Doing/To-DO:
- Reporting size per component
- Trying Tritonserver smaller base images: tf/pyt
- Rapids from internal image
- HugeCTR dependencies as optional

**Comment by albert17** [comment]
Component | Size (GB) | Size increase (GB)
-- | -- | --
Base | 12.4 |  0
System Packages | 12.7 | 0.3
Python Packages | 13.7 | 1
Cmake | 14 | 0.3
spdlog | 14 | 0
Arrow | 14.3 | 0.3
rmm | 14.3 | 0
cuDF | 14.9 | 0.6
Merlin Core | 14.9 | 0
Merlin NVTabular | 15 | 0.1
Merlin Transformers4Rec | 15.1 | 0.1
Merlin Models | 15.1 | 0
Merlin NVTabular Triton Backend | 15.1 | 0
Hiredis | 15.1 | 0
redis++ | 15.1 | 0
RocksDB | 15.4 | 0.3
LibRdKafka | 15.5 | 0.1
Java | 15.9 | 0.4
libhdfs | 17.1 | 1.2
HugeCTR | 17.9 | 0.8

**Comment by albert17** [comment]
Created 2 new images
- merlin-inference-tf: 12.6 GB
- merlin-inference-pyt: 13.4 GB

**Comment by viswa-nvidia** [comment]
@albert17 , please check off the completed items at the top of this ticket in the to do . Is there anything blocking for 22.03 ?

**Comment by albert17** [comment]
Completed. We have now 3 inference containers

**Comment by viswa-nvidia** [comment]
👍

**Comment by karlhigley** [comment]
🎉
