### ISSUE TITLE
merlin-core not installed in latest merlin-inference images

### ISSUE THREAD

**Issue by IamGianluca** [NVIDIA-Merlin/Merlin#127]
Hi,

I'm a big fan of your work (papers/code/tutorials)! Congrats!
 
I'm going through the tutorials in the `transformers4rec` repo and encountered this issue when trying to load any pre-trained ensembled model (nvtabular + pytorch).

```
I0305 04:19:13.236369 182 grpc_server.cc:4190] Started GRPCInferenceService at 0.0.0.0:8001
I0305 04:19:13.236600 182 http_server.cc:2857] Started HTTPService at 0.0.0.0:8000
I0305 04:19:13.278305 182 http_server.cc:167] Started Metrics Service at 0.0.0.0:8002
I0305 04:19:22.913046 182 model_repository_manager.cc:994] loading: t4r_pytorch_nvt:1
I0305 04:19:23.020783 182 python.cc:1905] TRITONBACKEND_ModelInstanceInitialize: t4r_pytorch_nvt (GPU device 0)
/nvtabular/nvtabular/workflow/workflow.py:339: UserWarning: Loading workflow generated with nvtabular version 0.11.0 - but we are running nvtabular 0.9.0+1.g31f9350. This might cause issues
  warnings.warn(
/nvtabular/nvtabular/workflow/workflow.py:339: UserWarning: Loading workflow generated with cudf version 21.12.00a+293.g0930f712e6 - but we are running cudf 21.10.00a+345.ge05bd4bf3c.dirty. This might cause issues
  warnings.warn(
0305 04:19:25.945803 210 pb_stub.cc:369] Failed to initialize Python stub: ModuleNotFoundError: No module named 'merlin'

At:
  /nvtabular/nvtabular/workflow/workflow.py(358): load
  /root/models/t4r_pytorch_nvt/1/model.py(60): initialize

E0305 04:19:25.947090 182 model_repository_manager.cc:1152] failed to load 't4r_pytorch_nvt' version 1: Internal: ModuleNotFoundError: No module named 'merlin'

At:
  /nvtabular/nvtabular/workflow/workflow.py(358): load
  /root/models/t4r_pytorch_nvt/1/model.py(60): initialize
```

It seems that the `merlin-core` library is not installed. I've also tried to open a python interpreter in the docker container and import some of the libraries (`nvtabular`, `transformers4rec`). They all seem to work but `merlin`. 

For comparison, when using the `merlin-pytorch-training:22.03` image, I can correctly import `merlin` from a python interpreter.

However, looking at the [docker image](https://github.com/NVIDIA-Merlin/Merlin/blob/23ac23a02f41a5f8ef35dcefc22a244f2e27218a/docker/inference/dockerfile.torch#L137) I can't see anything wrong. I'm not very familiar with the `merlin-core` codebase though, so perhaps I'm missing something.

Both 22.02 and nightly images seem to be affected by this issue.

**Comment by rnyak** [comment]
@IamGianluca thanks for reporting. we will update the notebooks eventually. You can install Merlin core via:

```
git clone https://github.com/NVIDIA-Merlin/core
cd core
pip install -e .
```

**Comment by IamGianluca** [comment]
That worked, thanks @rnyak
