### ISSUE TITLE
Add merlin-systems to the containers

### ISSUE THREAD

**Issue by benfred** [NVIDIA-Merlin/Merlin#152]
We've created the merlin-systems repo - and we should include this code inside all of our containers

**Comment by albert17** [comment]
Adding them to all training and inference

**Comment by albert17** [comment]
@benfred  Also:

Do we want transformers4 rec in training?

See current state of softwares installed: https://github.com/NVIDIA-Merlin/Merlin/pull/141

And let me know if anything should change
