### ISSUE TITLE
Support feature crossing (somehow)

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#171]
Open for discussion which library should support this

**Comment by viswa-nvidia** [comment]
@karlhigley , should we track this still?

**Comment by oliverholworthy** [comment]
For reference there is some feature crossing functionality in some of the models code today:

-  [`DotProductInteraction`](https://github.com/NVIDIA-Merlin/models/blob/6d47dd3872a1b3f332a76c483dcf8d3155429ef0/merlin/models/tf/blocks/interaction.py#L25) - used in the implementation of DLRM (computes a pairwise dot product of embeddings)
- [`CrossBlock`](https://github.com/NVIDIA-Merlin/models/blob/6d47dd3872a1b3f332a76c483dcf8d3155429ef0/merlin/models/tf/blocks/cross.py#L29) - used in the implementation of DCN
- [`HashedCross`](https://github.com/NVIDIA-Merlin/models/blob/6d47dd3872a1b3f332a76c483dcf8d3155429ef0/merlin/models/tf/core/transformations.py#L687) - recently added (within the last month) to support the Wide & Deep implementation.

**Comment by karlhigley** [comment]
@oliverholworthy Yeah, I think the question was about whether we should support that a feature pre-processing operation
