### ISSUE TITLE
[RMP] Set up unit tests for Merlin example notebooks

### ISSUE THREAD

**Issue by jperez999** [NVIDIA-Merlin/Merlin#205]
# All
- [x] #222
- [x] https://github.com/NVIDIA-Merlin/Merlin/issues/219

# Merlin Models

- [x] #226

# Merlin Systems

- [x] #225

# Merlin

- [x] #224

**Comment by bschifferer** [comment]
Migrate the NVT example notebook unit tests to use [Testbook](https://github.com/nteract/testbook)

@EvenOldridge @rnyak @mikemckiernan Radek and me talked yesterday, if we need to restructure/move the NVTabular examples. The NVTabular example contains components, which are not relevant anymore (training, deployment). I am not sure, if it make sense to migrate the unittests to testbook, now. I think we should define the new structure, first and add the unittests for the notebooks which will stay and/or add the new unittests in the new repo (where they will move)

**Comment by EvenOldridge** [comment]
Now that the initial unit tests are in place we should come up with a process for adding new ones as examples are added to the libraries.  @bschifferer can you work with me and @benfred to define this.
