### ISSUE TITLE
Update the Merlin examples to use a shared Docker volume

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#209]

**Comment by mikemckiernan** [comment]
Keeping some notes as I step through the process:

* I think in models/example/04... we need the foll change:
```python
# from
workflow.save('workflow')

# to
workflow_path = os.path.join(DATA_FOLDER, "workflow")
workflow.save(workflow_path)
```

**Comment by mikemckiernan** [comment]
For the systems example, if we're considering being prescriptive about the paths, then maybe change from:

```shell
tritonserver --model-repository=/ensemble_export_path/ --backend-config=tensorflow,version=2
```
to
```shell
tritonserver --model-repository=/workspace/data/ensemble ...
```
and indicate to specify a different path if you stepped off the happy path earlier.

**Comment by bschifferer** [comment]
When we move to the new container structure, do we still need a shared docker volume?

**Comment by rnyak** [comment]
@bschifferer normally we should not, but we did not test anything with the new containers yet.

**Comment by viswa-nvidia** [comment]
@mikemckiernan , can we close this ?

**Comment by bschifferer** [comment]
I guess this is related tot he old examples. We havent had time working on them, yet
