### ISSUE TITLE
Link notebooks to containers in a way that makes it clear which container a given notebook will run on.

### ISSUE THREAD

**Issue by EvenOldridge** [NVIDIA-Merlin/Merlin#219]
Provide a consistent way for notebooks to specify which container the notebook is intended to be run on. 

- [ ] A customer facing reference that's human readable.
- [ ]  Provide method to extract this (container) information from the notebook, so that it can be used by the NGC one button launch to select the appropriate container.

**Comment by bschifferer** [comment]
@jperez999 @karlhigley can we start working on this ticket? My last information was that we wanted to wait for the new unified container (training + inference per container).

**Comment by karlhigley** [comment]
It's fine to tag the notebooks against the existing containers for now. We'll have to tag them again once the new containers are available, but we're in the process of working through a bunch of CI and build process issues, so that might be a while.

**Comment by rnyak** [comment]
@bschifferer can we add a text on top of each notebook now for 22.05 release?
