### ISSUE TITLE
Create new pipelines for Docker container builds

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#241]
- [x] #388

**Comment by mikemckiernan** [comment]
As long as the library versions are available from `pip` or by importing the library and printing the version it'll be OK.  If there are grander ideas, I'm game to pitch in.

**Comment by karlhigley** [comment]
They should be, so I'm not sure if we need to do anything specific here, but wanted to make sure we didn't miss adding a crucial step to the new pipelines (if necessary.)
