### ISSUE TITLE
Nightly Containers Blocked on Numba/Numpy/Dask/Distributed version conflicts

### ISSUE THREAD

**Issue by jperez999** [NVIDIA-Merlin/Merlin#248]
We are getting collisions that stem from numba. The latest release of numba==0.55.1 and unfortunately that is pinned to numpy 1.21. On the nightly, they are using numpy 1.22, so we hit collisions trying to install our merlin source. They manifest as the following: 
```
pip._vendor.pkg_resources.ContextualVersionConflict: (distributed 2022.3.0 (/usr/local/lib/python3.8/dist-packages), Requirement.parse('distributed==2021.11.2'), {'nvtabular', 'merlin-core'})
[0mThe command '/bin/sh -c git clone https://github.com/NVIDIA-Merlin/NVTabular.git /nvtabular/ &&     cd /nvtabular/ && git checkout ${NVTAB_VER} && pip install -e . --no-deps' returned a non-zero code: 2
```
We need to decide the priority on updating these packages, if we move to numpy 1.22 and the latest dask we hit our normal errors of numpy related to using `.get()`.  Or do we downgrade the packages coming from upstream?

**Comment by karlhigley** [comment]
Are the issue with `.get()` fixable?

**Comment by jperez999** [comment]
I think they come from within dask and its access api. I am not sure, would require further investigation. @rjzamora do you know about these compatibility errors?

I am think I am just try to change == for dask and distributed to >=, thoughts?

**Comment by rjzamora** [comment]
>I think they come from within dask and its access api. I am not sure, would require further investigation. @rjzamora do you know about these compatibility errors?

Is there an issue related to this? (or any related discussion on github). Sorry - My memory is failing me.

**Comment by benfred** [comment]
@jperez999 has an initial set of fixes here with https://github.com/NVIDIA-Merlin/core/pull/81 / https://github.com/NVIDIA-Merlin/NVTabular/pull/1536 / https://github.com/NVIDIA-Merlin/models/pull/412 / https://github.com/NVIDIA-Merlin/systems/pull/98 .
