### ISSUE TITLE
[RMP] RecSys Tutorial

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#270]
- [ ] What's the scope of this tutorial?
- [ ] Will it include?
  - [ ] Retrieval/ranking models
  - [ ] Transformer models (in MM?)
  - [ ] XGBoost/FIL
  - [ ] Merlin Systems

**Comment by karlhigley** [comment]
@bschifferer @rnyak Have we already submitted a proposal for this tutorial? If so, could we link to it from this issue?

**Comment by bschifferer** [comment]
The proposal deadline is May 18th. We will work on it this and next week

**Comment by EvenOldridge** [comment]
@bschifferer @rnyak Is this a duplicate of https://github.com/NVIDIA-Merlin/Merlin/issues/286
