### ISSUE TITLE
Automate release note generation using release-drafter

### ISSUE THREAD

**Issue by benfred** [NVIDIA-Merlin/Merlin#315]

**Comment by benfred** [comment]
PR's in all the different repos:

https://github.com/NVIDIA-Merlin/models/pull/439
https://github.com/NVIDIA-Merlin/core/pull/88 
https://github.com/NVIDIA-Merlin/systems/pull/103
https://github.com/NVIDIA-Merlin/systems/pull/107 
https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/415 
https://github.com/NVIDIA-Merlin/Merlin/pull/308

**Comment by mikemckiernan** [comment]
Each of the repos has a request in the CONTRIBUTING document to use labels.  Each repo has at least one label for each of the categories.  Closing.
