### ISSUE TITLE
ENV pythonpath update breaks environment

### ISSUE THREAD

**Issue by jperez999** [NVIDIA-Merlin/Merlin#330]
This line https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/training/dockerfile.tf#L116

messes up environment... nothing else can be installed in the python environment, specifically using pip.

**Comment by benfred** [comment]
We've changed hugectr to not require the PYTHONPATH in https://github.com/NVIDIA-Merlin/HugeCTR/pull/320 ,
