### ISSUE TITLE
Getting error while connecting to merlin through docker container

### ISSUE THREAD

**Issue by sejal9507** [NVIDIA-Merlin/Merlin#339]
Getting error while connecting to merlin through docker container by using this command:
docker run --gpus all --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host --cap-add SYS_NICE [nvcr.io/nvidia/merlin/merlin-training:22.03](http://nvcr.io/nvidia/merlin/merlin-training:22.03) /bin/bash

Error:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown.

**Comment by rnyak** [comment]
@sejal9507 can you provide more detail about your HW and your driver version? can you share the print outs from the commands below by executing them in your terminal:
```
nvidia-smi
nvcc --version
```

thanks.

**Comment by sejal9507** [comment]
azureuser@ngc-vm:~$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
azureuser@ngc-vm:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

**Comment by sejal9507** [comment]
<img width="309" alt="Capture nvidia" src="https://user-images.githubusercontent.com/80972124/170973711-8cfb7146-e1d7-4aaf-9590-36f8c0e9a8ac.PNG">

**Comment by sejal9507** [comment]
GPU - V100
Linux (ubuntu 18.04)

**Comment by sejal9507** [comment]
GPU - V100
Linux (ubuntu 18.04)
Using Azure Virtual Machine

**Comment by sejal9507** [comment]
Yes,exactly I was not able to see the GPU when executing this command nvidia-smi.
azureuser@ngc-vm:~$ nvidia-smi
Failed to initialize NVML: Driver/library version mismatch

Can you give me the commands?

**Comment by jperez999** [comment]
@sejal9507  Can you try a more updated container. It seems your  not able to load in the cuda version on the docker container. So it tries to rely on the bare metal cuda, which might not be updated... If you can try the 22.05 container set and let us know if you hit same problem that might help verify if that is the issue.

**Comment by sejal9507** [comment]
(merlin) root@ngc-vm:~# docker run --gpus all --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host --cap-add SYS_NICE nvcr.io/nvidia/merlin/merlin-training:22.05 /bin/bash

docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown.

**Comment by sejal9507** [comment]
I have executed this command - sudo apt-get install -y cuda-compat-11-5
<img width="947" alt="cuda" src="https://user-images.githubusercontent.com/80972124/172370630-a9b8bbd9-8177-45ce-8cfc-75e1e4e173b7.PNG">

**Comment by rnyak** [comment]
@sejal9507 closing this issue since we did not hear back from you. Please reopen in case you still have an issue.
