### ISSUE TITLE
Running example codes on A100

### ISSUE THREAD

**Issue by bpark-nvidia** [NVIDIA-Merlin/Merlin#346]
I tried to run the example codes on an A100 machine, and I ran into an error when I tried to set a server with `tritonserver`. The two main error messages are `ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")` and `Failed to place the graph without changing the devices of some resources. Some of the operations (that be colocated with resource generating operations) are not supported on the resources' devices`. I tried on a V100 machine, and it works fine. I am currently using nvcr.io/nvidia/merlin/merlin-tensorflow-inference:22.05 container for both cases.

**Comment by rnyak** [comment]
@jperez999 and @karlhigley fyi.

**Comment by rnyak** [comment]
@bpark-nvidia you can ignore `The two main error messages are ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")` error if you are seeing `successfully loaded faiss` msg afterwards. You can checkout this relevant issue : https://github.com/kyamagu/faiss-wheels/issues/39 which tells we can safely ignore this error msg.

**Comment by jperez999** [comment]
we may need to rebuild faiss to support SM80 (A100)

**Comment by EvenOldridge** [comment]
@bpark-nvidia our container now supports Faiss on A100.
