### ISSUE TITLE
[QST] Unexpected behaviour while serving multi-stage recommender system with Triton

### ISSUE THREAD

**Issue by future-xy** [NVIDIA-Merlin/Merlin#374]
# Triton reuses model.py of the first model

## Details
Triton reuses model.py of the first model (i.e. ```poc_ensemble/0_queryfeast/1/model.py``` in the multi-stage recommender system example) while ignoring model.py files of any other models, such as ```2_queryfaiss,  3_queryfeast,  4_unrollfeatures, 6_softmaxsampling```. However, Triton does load the correct config.pbtxt for each model.

It's easy to confirm this problem by adding ```print()``` in model.py, either ```initialize``` or ```execute``` for each model. I found the ```print()``` in ```poc_ensemble/0_queryfeast/1/model.py``` executed 5 times while others didn't.

It seems Triton only uses the model.py of the first model. The model ensemble can still work even if I delete all model.py except the first one, that is, ```poc_ensemble/0_queryfeast/1/model.py```. 

All these models use nvtabular as the backend. Is it a problem of nvtabular?

---
This problem, of course, doesn't affect the example because all these model.py files are copied from the same source but it is still quite wired.

---
I'm using nvcr.io/nvidia/merlin/merlin-tensorflow-inference   22.05

**Comment by karlhigley** [comment]
Not sure if this is still an issue, but if it is, we expect this issue to be resolved by upcoming work to migrate Systems ensemble graph execution off of Triton ensembles and into a single `TritonPythonModel`.
