### ISSUE TITLE
[Task] Update criteo links in example notebooks

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#397]
Criteo link updates needed:

## NVTabular:
NVTabular/examples/scaling-criteo/01-Download-Convert.ipynb 
Change "http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_" to "https://storage.googleapis.com/criteo-cail-datasets/day_"
NVTabular/examples/tensorflow/accelerating-tensorflow.ipynb
change the link of "Criteo Terabyte Dataset" from "https://labs.criteo.com/2013/12/download-terabyte-click-logs-2/" to "https://ailab.criteo.com/download-criteo-1tb-click-logs-dataset/

## HugeCTR
HugeCTR/notebooks/continuous_training.ipynb2
Change "http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_1.gz" to "https://storage.googleapis.com/criteo-cail-datasets/day_1.gz"
same change for page https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/samples/criteo
HugeCTR/notebooks/hugectr_wdl_prediction.ipynb
Change "http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_0.gz" to "https://storage.googleapis.com/criteo-cail-datasets/day_0.gz"
HugeCTR/notebooks/hugectr_criteo.ipynb
Change "http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_1.gz" to "https://storage.googleapis.com/criteo-cail-datasets/day_1.gz"
HugeCTR/notebooks/hugectr2onnx_demo.ipynb
Change "http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_1.gz" to "https://storage.googleapis.com/criteo-cail-datasets/day_1.gz"

**Additional context**
Add any other context, code examples, or references to existing implementations about the task here.

**Comment by mikemckiernan** [comment]
Fixed by https://github.com/NVIDIA-Merlin/NVTabular/pull/1591 and https://github.com/NVIDIA-Merlin/HugeCTR/pull/327.  FWIW, Emma did the work for HugeCTR.
