### ISSUE TITLE
[RMP] Decouple InputBlock from Embedding creation allowing for user defined embeddings

### ISSUE THREAD

**Issue by marcromeyn** [NVIDIA-Merlin/Merlin#404]
## Problem:
Customers want to be able to create embeddings that support a wide variety of options.  Currently InputBlock handles the selection of these features through arguments, however we're up to *18* arguments and it's only going to get worse.

By separating input block definition from embedding creation we can allow for a much more flexible set of embeddings support with a simpler API.

## Goal:
- Decouple `InputBlock` from Embedding creation 
- Reduce number of parameters of the `InputBlock` to a bare minimum without losing flexibility.
- Allow for customization of embeddings including support for parallel embeddings

## Constraints:
- Embedding creation should be decoupled from the input block
- Definition of embedding sizes should be mappable from the input block's representation of the schema file.

### 22.07
- [x] Create `EmbeddingTable`
### 22.08
- [x] NVIDIA-Merlin/models#580
- [x] NVIDIA-Merlin/models#579

### Proposed Potential API
```python
import merlin.models.tf as mm

def InputBlock(
	schema: Schema, 
	embeddings: Optional[Block] = None,
	continuous_projection: Optional[Block] = None,
	continuous_column_selector=ColumnSelector(Tags.CONTINUOUS)
	pre=None, 
	post=None, 
	aggregation=None
):
	embeddings = embeddings or mm.InferEmbeddings(schema)
	if continuous_projection:
		continuous = mm.TabularBlock(
			column_selector=continuous_column_selector,
			aggregation="concat"
		)
		continuous = continuous.connect(continuous_projection)
	else:
		continuous = mm.TabularBlock(
			column_selector=continuous_column_selector
		)
	
	return mm.ParallelBlock(
		dict(continuous=continuous, embeddings=embeddings),
		pre=pre,
		post=post,
		aggregation=aggregation
	)
```

```python
def InferEmbeddings(
	schema, 
	pre=None, 
	post=None, 
	aggregation=None,
	block_name="embeddings"
):
	cols = schema.select_by_tag(Tags.CATEGORICAL)
	tables = []

	for col in cols:
		tables.append(EmbeddingTable(dim=32, col))

	return ParallelBlock(
		*tables, 
		pre=pre,
		post=post,
		aggregation=aggregation,
		block_name=block_name
	)
```

**Comment by sohn21c** [comment]
re: "to create embeddings that support a wide variety of options"
>> Can you please elaborate on the options we'd like to support with the proposed feature?

**Comment by viswa-nvidia** [comment]
Gabriel to create a separate RMP ticket to track integration with higher level APIs
