### ISSUE TITLE
[RMP] Support negative-sampling for ranking

### ISSUE THREAD

**Issue by marcromeyn** [NVIDIA-Merlin/Merlin#413]
## Problem:
The big majority of our customers are training their models on implicit feedback and therefore typically only have positive interactions and need some strategy to sample negatives. 

As of now, we only have limited support for negative sampling in retrieval models and no support for other use-cases.

![CleanShot 2022-06-23 at 13 19 18](https://user-images.githubusercontent.com/3015785/175287026-1d399aab-9d77-4028-91e5-9f82985951bb.png)

## Goal:
- Make negative-sampling for retrieval + session-based more configurable
- Allow saving of models with negative-sampling
- Add negative-sampling for ranking

## Constraints:
- Sampling should be performant.

### 22.07
 - [x] #446
### 22.08
@marcromeyn  Add details here

**Comment by rnyak** [comment]
That's a required feature for KDD tutorial content, which we are now trying to do it with a manual custom way.

**Comment by viswa-nvidia** [comment]
Negative sampling for ranking is the current priority and is the focus for 22.07

**Comment by sohn21c** [comment]
What negative sampling algorithms are we implementing for retrieval, ranking, and session-based? We have 4 of them implemented in Merlin Models [link](https://nvidia-merlin.github.io/models/main/api.html#sampling)

**Comment by viswa-nvidia** [comment]
@marcromeyn , please update this ticket for negative sampling refactoring for retrieval

**Comment by viswa-nvidia** [comment]
changed the scope of this ticket from retrieval and ranking to ranking only. Retrieval code refactor is tracked separately.
