### ISSUE TITLE
[QST] Building-and-deploying-multi-stage-RecSys with custom dataset

### ISSUE THREAD

**Issue by sontung2310** [NVIDIA-Merlin/Merlin#437]
❓ Questions & Help
Hi! Thanks for providing the multi-stage recommender system example. This is really helpful to learn to use Merlin in a more realistic scenario. I'm trying to run Building-and-deploying-multi-stage-RecSys with custom dataset. 
However, I have some problem when doing this:

- When I trying to train the both Retrieval Model and Ranking model, the val_loss_total is became higher as well as training epochs increase. I also trying to train more epochs in your examples and got same problem. When I train with just few epoch, the model seem like being underfitting. But the more epochs training, the worser model is.
![image](https://user-images.githubusercontent.com/62052338/177459322-e9765301-ea01-436d-b7f7-cd60619e259c.png)

- I want to save Retrieval Model after training to get item embeddings. But I got this error (in the picture below). In your examples, we can only save model.retrieval_block.query_block(). So how can we save the entire model?
![image](https://user-images.githubusercontent.com/62052338/177461337-4b31f595-7246-46e1-b88a-726c09fec03f.png)

I am using merlin-tensorflow-inference:22.05 version.
Could you please help me figure out a solution? Thanks!

**Comment by rnyak** [comment]
@sontung2310 is this still an issue for you? can you please check out our examples and rerun with your `merlin-tensorflow:22.07`  (or the latest tag) notebook? 

Also please note that you cannot save entire Two-tower model now, you can save query tower. Please  follow this example  [01-Building-Recommender-Systems-with-Merlin.ipynb](https://github.com/NVIDIA-Merlin/Merlin/blob/main/examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb) which shows how to extract item embeddings.

**Comment by sontung2310** [comment]
@rnyak Have you ever trying to training with more epochs than one in both retrieval model and two tower model? Did the val_loss_total is became higher as well as training epochs increase? 

Also in your examples, item_embs was extracted by entire query model not only query block. (**item_embeddings** was the method of entire model **model_tt**) 

![image](https://user-images.githubusercontent.com/62052338/192181448-6a190d33-f76e-4537-8e0b-274ed0456529.png)

**Comment by rnyak** [comment]
@sontung2310  for your question `Also in your examples, item_embs was extracted by entire query model not only query block. (item_embeddings was the method of entire model model_tt)` 

Yes, this is how it works now. 

This examples are not doing any HPO.  val_loss might be increasing when you train longer. so you can do HPO at your end.
