### ISSUE TITLE
[BUG] Issue in running Merlin Containers on quick deploy

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#447]
### Bug description
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-training?quick-deploy=false  . After deploying and opening the jupyterlab it got stuck in the loading kernel step. This applies to  Merlin training and Merlin Pytorch training. Both of them had this issue. 

< To be updated > 
### Steps/Code to reproduce bug

1. 
2. 
3. 

### Environment details
- Merlin version: 
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

**Comment by viswa-nvidia** [comment]
@benfred , please update the status for this ticket. Can this be closed? if not, does this qualify for P0 ?

in the email thread, this was the last communication from Shokoufeh Monjezi Kouchak 

Clone this bug https://nvbugs/3597709 .  In the bug, explain that you have these containers already published, you want to add quick deploy feature to them. And ask them to add these containers to vertexAI workbench collection after adding quick deploy.

**Comment by EvenOldridge** [comment]
@bschifferer @rnyak can one of you validate that our vertex AI workbench workflow is working.  @nv-alaiacano @benfred We need a better way of tracking whether this is up to date and working or not.

**Comment by nv-alaiacano** [comment]
Is it correct that `merlin-training` is deprecated in favor of `merlin-tensorflow`, `merlin-pytorch`, etc?

**Comment by EvenOldridge** [comment]
Yeah, we used to have to split them by training and inference for container
size reasons.

**Comment by EvenOldridge** [comment]
@bbozkaya has filed an NVBug to get the container to deploy with content rather than empty.  Waiting on NGC team.

**Comment by bbozkaya** [comment]
I re-contacted NGC team to remind them about this issue/bug. I hope they can resolve it.

**Comment by bbozkaya** [comment]
Containers are updated to 22.10; older containers are removed. Notebook collections are also updated to the latest versions with additional notebooks included. Notebooks appear in a folder in the corresponding container when quick deployed from NGC to Vertex AI. Notebooks are tested and they run without issues.
