### ISSUE TITLE
[BUG] Facing pyarrow error while using feast in 01-Building-Recommender-Systems-with-Merlin example.

### ISSUE THREAD

**Issue by m-hammad-khan** [NVIDIA-Merlin/Merlin#495]
# ❓ Questions & Help

## Details

While running merlin 01-Building-Recommender-Systems-with-Merlin.ipynb example I am facing this issue. Currently, I am using NVIDIA pre-built image https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-tensorflow-training. I have tried `pip install pyarrow` but nothing changed.

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/97903979/181919525-3dc351ad-c029-43a0-a881-5371df268103.png">

**Comment by rnyak** [comment]
@m-hammad-khan please use `merlin-tensorflow:22.06` container. It has both tensorflow and triton inference server installed, so you should not be getting the `pyarrow` error you get above. You only need to install `feast` and  `faiss-gpu`. You can run the following command in a jupyter cell:

`%pip install "feast<0.20" faiss-gpu`

**Comment by karlhigley** [comment]
Yeah, we had to make some updates to the containers to build PyArrow with S3 support, since Feast requires it even if you're not using S3. 😕  Like @rnyak said though, the newer containers should have what you need pre-installed.

**Comment by m-hammad-khan** [comment]
Thanks, @karlhigley @rnyak it works fine on the `merlin-tensorflow:22.06` image.
