### ISSUE TITLE
[QST] Facing triton server out of memory error while running Merlin example. 

### ISSUE THREAD

**Issue by m-hammad-khan** [NVIDIA-Merlin/Merlin#519]
# ❓ Questions & Help

## Details

I am getting this error while running the triton server. I am currently using the `merlin-tensorflow:22.06` container on AWS EC2 `p3-2xlarge-gpu` instance. I have also restricted the dataset size to 10_000. 

<img width="903" alt="image" src="https://user-images.githubusercontent.com/97903979/183429116-d9540b42-315b-49ca-86e9-81418d3c90fc.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/97903979/183427565-57e2d8fe-1c18-4ff7-9911-f6e48904ff02.png">

`tritonserver --model-repository=/Merlin/examples/Building-and-deploying-multi-stage-RecSys/poc_ensemble --backend-config=tensorflow,version=2`

> root@hammad-merlin-tensorflow-test:/Merlin/examples/Building-and-deploying-multi-stage-RecSys# tritonserver --model-repository=/Merlin/examples/Building-and-deploying-multi-stage-RecSys/poc_ensemble --backend-config=tensorflow,version=2
I0808 13:11:10.199151 1485 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f71ae000000' with size 268435456
I0808 13:11:10.199645 1485 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0808 13:11:10.204904 1485 model_repository_manager.cc:1191] loading: 0_queryfeast:1
I0808 13:11:10.305140 1485 model_repository_manager.cc:1191] loading: 1_predicttensorflow:1
I0808 13:11:10.308841 1485 python.cc:2388] TRITONBACKEND_ModelInstanceInitialize: 0_queryfeast (GPU device 0)
E0808 13:11:10.325940 1485 model_repository_manager.cc:1348] failed to load '0_queryfeast' version 1: Internal: Unable to initialize shared memory key 'triton_python_backend_shm_region_1' to requested size (67108864 bytes). If you are running Triton inside docker, use '--shm-size' flag to control the shared memory region size. Each Python backend model instance requires at least 64MBs of shared memory. Error: No such file or directory
I0808 13:11:10.405323 1485 model_repository_manager.cc:1191] loading: 2_queryfaiss:1
I0808 13:11:10.505531 1485 model_repository_manager.cc:1191] loading: 3_queryfeast:1
I0808 13:11:10.605759 1485 model_repository_manager.cc:1191] loading: 4_unrollfeatures:1
I0808 13:11:10.706037 1485 model_repository_manager.cc:1191] loading: 5_predicttensorflow:1
I0808 13:11:10.741680 1485 tensorflow.cc:2181] TRITONBACKEND_Initialize: tensorflow
I0808 13:11:10.741716 1485 tensorflow.cc:2191] Triton TRITONBACKEND API version: 1.9
I0808 13:11:10.741749 1485 tensorflow.cc:2197] 'tensorflow' TRITONBACKEND API version: 1.9
I0808 13:11:10.741768 1485 tensorflow.cc:2221] backend configuration:
{"cmdline":{"auto-complete-config":"false","backend-directory":"/opt/tritonserver/backends","min-compute-capability":"6.000000","version":"2","default-max-batch-size":"4"}}
I0808 13:11:10.741835 1485 tensorflow.cc:2281] TRITONBACKEND_ModelInitialize: 1_predicttensorflow (version 1)
I0808 13:11:10.744538 1485 tensorflow.cc:2330] TRITONBACKEND_ModelInstanceInitialize: 1_predicttensorflow (GPU device 0)
I0808 13:11:10.806338 1485 model_repository_manager.cc:1191] loading: 6_softmaxsampling:1
I0808 13:11:10.910548 1485 tensorflow.cc:2368] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0808 13:11:10.910567 1485 python.cc:2388] TRITONBACKEND_ModelInstanceInitialize: 2_queryfaiss (GPU device 0)
I0808 13:11:10.910627 1485 tensorflow.cc:2307] TRITONBACKEND_ModelFinalize: delete model state
E0808 13:11:10.910663 1485 model_repository_manager.cc:1348] failed to load '1_predicttensorflow' version 1: Internal: unable to create stream: out of memory
I0808 13:11:10.914318 1485 python.cc:2388] TRITONBACKEND_ModelInstanceInitialize: 3_queryfeast (GPU device 0)
E0808 13:11:10.914326 1485 model_repository_manager.cc:1348] failed to load '2_queryfaiss' version 1: Internal: unable to create stream: out of memory
I0808 13:11:10.918232 1485 python.cc:2388] TRITONBACKEND_ModelInstanceInitialize: 4_unrollfeatures (GPU device 0)
E0808 13:11:10.918244 1485 model_repository_manager.cc:1348] failed to load '3_queryfeast' version 1: Internal: unable to create stream: out of memory
I0808 13:11:10.921039 1485 tensorflow.cc:2281] TRITONBACKEND_ModelInitialize: 5_predicttensorflow (version 1)
E0808 13:11:10.921056 1485 model_repository_manager.cc:1348] failed to load '4_unrollfeatures' version 1: Internal: unable to create stream: out of memory
I0808 13:11:10.922273 1485 tensorflow.cc:2330] TRITONBACKEND_ModelInstanceInitialize: 5_predicttensorflow (GPU device 0)
I0808 13:11:10.925973 1485 tensorflow.cc:2368] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0808 13:11:10.925984 1485 python.cc:2388] TRITONBACKEND_ModelInstanceInitialize: 6_softmaxsampling (GPU device 0)
I0808 13:11:10.926029 1485 tensorflow.cc:2307] TRITONBACKEND_ModelFinalize: delete model state
E0808 13:11:10.926090 1485 model_repository_manager.cc:1348] failed to load '5_predicttensorflow' version 1: Internal: unable to create stream: out of memory
E0808 13:11:10.929664 1485 model_repository_manager.cc:1348] failed to load '6_softmaxsampling' version 1: Internal: unable to create stream: out of memory
E0808 13:11:10.929749 1485 model_repository_manager.cc:1551] Invalid argument: ensemble 'ensemble_model' depends on '6_softmaxsampling' which has no loaded version
I0808 13:11:10.929808 1485 server.cc:556] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0808 13:11:10.929867 1485 server.cc:583] 
+------------+----------------------------------------------------------+----------------------------------------------------------+
| Backend    | Path                                                     | Config                                                   |
+------------+----------------------------------------------------------+----------------------------------------------------------+
| python     | /opt/tritonserver/backends/python/libtriton_python.so    | {"cmdline":{"auto-complete-config":"false","min-compute- |
|            |                                                          | capability":"6.000000","backend-directory":"/opt/tritons |
|            |                                                          | erver/backends","default-max-batch-size":"4"}}           |
| tensorflow | /opt/tritonserver/backends/tensorflow2/libtriton_tensorf | {"cmdline":{"auto-complete-config":"false","backend-dire |
|            | low2.so                                                  | ctory":"/opt/tritonserver/backends","min-compute-capabil |
|            |                                                          | ity":"6.000000","version":"2","default-max-batch-size":" |
|            |                                                          | 4"}}                                                     |
|            |                                                          |                                                          |
+------------+----------------------------------------------------------+----------------------------------------------------------+

I0808 13:11:10.930021 1485 server.cc:626] 
+---------------------+---------+---------------------------------------------------------------------------------------------------+
| Model               | Version | Status                                                                                            |
+---------------------+---------+---------------------------------------------------------------------------------------------------+
| 0_queryfeast        | 1       | UNAVAILABLE: Internal: Unable to initialize shared memory key 'triton_python_backend_shm_region_1 |
|                     |         | ' to requested size (67108864 bytes). If you are running Triton inside docker, use '--shm-size' f |
|                     |         | lag to control the shared memory region size. Each Python backend model instance requires at leas |
|                     |         | t 64MBs of shared memory. Error: No such file or directory                                        |
| 1_predicttensorflow | 1       | UNAVAILABLE: Internal: unable to create stream: out of memory                                     |
| 2_queryfaiss        | 1       | UNAVAILABLE: Internal: unable to create stream: out of memory                                     |
| 3_queryfeast        | 1       | UNAVAILABLE: Internal: unable to create stream: out of memory                                     |
| 4_unrollfeatures    | 1       | UNAVAILABLE: Internal: unable to create stream: out of memory                                     |
| 5_predicttensorflow | 1       | UNAVAILABLE: Internal: unable to create stream: out of memory                                     |
| 6_softmaxsampling   | 1       | UNAVAILABLE: Internal: unable to create stream: out of memory                                     |
+---------------------+---------+---------------------------------------------------------------------------------------------------+

I0808 13:11:10.941078 1485 metrics.cc:650] Collecting metrics for GPU 0: Tesla V100-SXM2-16GB
I0808 13:11:10.941374 1485 tritonserver.cc:2138] 
+----------------------------------+------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                          |
+----------------------------------+------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                         |
| server_version                   | 2.22.0                                                                                         |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy m |
|                                  | odel_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace |
| model_repository_path[0]         | /Merlin/examples/Building-and-deploying-multi-stage-RecSys/poc_ensemble                        |
| model_control_mode               | MODE_NONE                                                                                      |
| strict_model_config              | 1                                                                                              |
| rate_limit                       | OFF                                                                                            |
| pinned_memory_pool_byte_size     | 268435456                                                                                      |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                       |
| response_cache_byte_size         | 0                                                                                              |
| min_supported_compute_capability | 6.0                                                                                            |
| strict_readiness                 | 1                                                                                              |
| exit_timeout                     | 30                                                                                             |
+----------------------------------+------------------------------------------------------------------------------------------------+

I0808 13:11:10.941418 1485 server.cc:257] Waiting for in-flight requests to complete.
I0808 13:11:10.941433 1485 server.cc:273] Timeout 30: Found 0 model versions that have in-flight inferences
I0808 13:11:10.941452 1485 server.cc:288] All models are stopped, unloading models
I0808 13:11:10.941468 1485 server.cc:295] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models
W0808 13:11:11.943000 1485 metrics.cc:507] Unable to get memory usage for GPU 0. Memory usage status:Success, value:0. Memory total status:Success, value:0
root@hammad-merlin-tensorflow-test:/Merlin/examples/Building-and-deploying-multi-stage-RecSys#

**Comment by rnyak** [comment]
@m-hammad-khan we have two notebooks under `Building-and-deploying-multi-stage-RecSys`. when you execute the first one, and move to the second notebook, please shutdown the first, so that you can free the GPU memory. is that the way you are following? 

Also this is how launch my container locally 
```
docker run -it --gpus device=1 --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p 8000:8000 -p 8001:8001 -p 8002:8002 -p 8888:8888 --ipc=host nvcr.io/nvidia/merlin/merlin-tensorflow:22.06
```

using `shm-size` and other extra flags might help.

**Comment by m-hammad-khan** [comment]
@rnyak  yes I have closed the first notebook to free up the GPU memory, let me try using `shm-size` flag.

**Comment by m-hammad-khan** [comment]
@rnyak it works perfectly now, thanks!
