### ISSUE TITLE
[Task] Adding download tracking on Merlin examples

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#551]
Note: This is a task that must be listed under a strategic initiative. Revisit this during the backlog grooming

## Goal: 
To allow tracking on Merlin assets on github repo 

## Scope:
Merlin examples to contain uniquely named images to allow tracking download counts 

Note:
https://docs.google.com/presentation/d/1NVZhtFkCHm_cOq5SpTqR6heMUWMyJZ2Xsjfywdk0VeI/edit#slide=id.g13ccf79b500_0

**Comment by viswa-nvidia** [comment]
@sohn21c , this is a  task that must be listed under a strategic initiative. What is the initiative ?

**Comment by EvenOldridge** [comment]
@viswa-nvidia This is a minor task, not a roadmap level issue

**Comment by mikemckiernan** [comment]
Closing this task as a dup of https://github.com/NVIDIA-Merlin/Merlin/issues/546.
