### ISSUE TITLE
[Task] Create a set of notebooks (data preprocessing, model training) on the H&M data

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/Merlin#593]
### Description

The goal is to create a set of notebooks on the H&M data. This might be a nice way to demonstrate data preprocessing and various models.

**Additional context**

This could genuinely be interesting to the public. Additionally, it would give me a chance to experiment a bit more with the DCN and DLRM model before the GTC session (will begin researching these models to make sure I fully understand them now!)

**Comment by bschifferer** [comment]
I close that ticket as we have many examples. We can reopen it, if we have a use case for H&M dataset.
