### ISSUE TITLE
[Task] Report Notebook unittest/CI

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/Merlin#600]
### Description
Create a report which notebook unit tests and CI are executed in which test environment (nightly CI, Jenkins, github actions, etc.) for all repos

**Comment by karlhigley** [comment]
You may find [this spreadsheet of example notebook coverage per container](https://docs.google.com/spreadsheets/d/1yJJK1CPqs6KShrZeAFH9G0FL-TlZN5LWU0tpaaFzR04/edit#gid=0) useful
