### ISSUE TITLE
[BUG] remove `--user` from Dockerfile in both inference and training

### ISSUE THREAD

**Issue by mengdong** [NVIDIA-Merlin/Merlin#62]
In current NGC containers some pythons packages are installed with a --user option for the root user.
In managed notebooks, containers are run as in the context of the jupyter user, which means that some packages fail to run.

This will prevent run Merlin docker as other user generally as well.  @sohn21c

**Comment by benfred** [comment]
The ```--user``` flag has also caused problems like https://github.com/NVIDIA-Merlin/Merlin/issues/57 . I think we should remove if possible.

**Comment by albert17** [comment]
@mengdong Created PR #64 to address this problem. We cannot refresh 21.11 container, but the nightly containers will have this change when merged.
