### ISSUE TITLE
[BUG] Error while running "Deploying multi-stage RecSys with Merlin Systems" notebook

### ISSUE THREAD

**Issue by kebitmatf** [NVIDIA-Merlin/Merlin#654]
### Bug description

Running your newest update 02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
at link: [https://github.com/NVIDIA-Merlin/Merlin/blob/main/examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb]

response = send_triton_request(request_schema, request, outputs)
response

I got error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [26], line 1
----> 1 response = send_triton_request(request_schema, request, outputs)
      2 response

File /usr/local/lib/python3.8/dist-packages/merlin/systems/triton/utils.py:134, in send_triton_request(df, outputs_list, client, endpoint, request_id, triton_model)
    131     except Exception as e:
    132         raise e
--> 134 if not client.is_server_live():
    135     raise ValueError("Client could not establish commuincation with Triton Inference Server.")
    137 inputs = triton.convert_df_to_triton_input(df.columns, df, grpcclient.InferInput)

AttributeError: 'list' object has no attribute 'is_server_live'

If I run the old version on the example/Building-and-deploying-multi-stage-RecSys in the Container. It's OK.
So, the new update has mistakes?

### Steps/Code to reproduce bug

1. 
2. 
3. 

### Environment details
- Merlin version: 22.05 Tensorflow Inference
- Platform: 
- Python version: 3.8
- PyTorch version (GPU?):
- Tensorflow version (GPU?): 2.8

**Comment by nv-alaiacano** [comment]
Thanks for the bug report! It is possible that the examples in the `main` branch become broken between releases. The examples included in any of our [published docker containers](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-tensorflow/tags) _should_ be stable.

We released 22.09 just a week or so ago, which should contain much more recent examples than the 22.05 container you were using. Could you give that a try to confirm that they work in there?

**Comment by bschifferer** [comment]
@kebitmatf Hello, I just ran the unittest for the example on the latest container. Can you test the example on the 22.09 container?

**Comment by mzurek-teldoc** [comment]
I have `ValueError: Missing columns ['click/binary_classification_task'] found in operatorSubsetColumns during compute_input_schema.` when running `ensemble = Ensemble(ordering, request_schema)` in the notebook...

**Comment by rnyak** [comment]
@mzurek-teldoc  and @kebitmatf  are you still having errors? Can you  please test `merlin-tensorflow:22.12` image? thanks.

**Comment by rnyak** [comment]
@mzurek-teldoc do you still have the issue? we did not hear from you so I am closing this ticket please reopen if the issue remains.
