### ISSUE TITLE
gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ng-fukgin** [NVIDIA-Merlin/Merlin#66]
When i run 04a-Triton-Inference-with-TF.ipynb on local computer （without docker），i meet some error in  _triton_client.is_server_live()_ ，there is the error 

"
 ---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
~/anaconda3/envs/merlin/lib/python3.7/site-packages/geventhttpclient/connectionpool.py in get_socket(self)
    162         try:
--> 163             return self._socket_queue.get(block=False)
    164         except gevent.queue.Empty:

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/_gevent_cqueue.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cqueue.Queue.get()

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/_gevent_cqueue.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cqueue.Queue.get()

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/_gevent_cqueue.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cqueue.Queue._Queue__get_or_peek()

Empty: 

During handling of the above exception, another exception occurred:

gaierror                                  Traceback (most recent call last)
/tmp/ipykernel_10740/1716762689.py in <module>
----> 1 triton_client.is_server_live()

~/anaconda3/envs/merlin/lib/python3.7/site-packages/tritonclient/http/__init__.py in is_server_live(self, headers, query_params)
    341         response = self._get(request_uri=request_uri,
    342                              headers=headers,
--> 343                              query_params=query_params)
    344 
    345         return response.status_code == 200

~/anaconda3/envs/merlin/lib/python3.7/site-packages/tritonclient/http/__init__.py in _get(self, request_uri, headers, query_params)
    264             response = self._client_stub.get(request_uri, headers=headers)
    265         else:
--> 266             response = self._client_stub.get(request_uri)
    267 
    268         if self._verbose:

~/anaconda3/envs/merlin/lib/python3.7/site-packages/geventhttpclient/client.py in get(self, request_uri, headers)
    264 
    265     def get(self, request_uri, headers={}):
--> 266         return self.request(METHOD_GET, request_uri, headers=headers)
    267 
    268     def head(self, request_uri, headers=None):

~/anaconda3/envs/merlin/lib/python3.7/site-packages/geventhttpclient/client.py in request(self, method, request_uri, body, headers)
    224 
    225         while 1:
--> 226             sock = self._connection_pool.get_socket()
    227             try:
    228                 _request = request.encode()

~/anaconda3/envs/merlin/lib/python3.7/site-packages/geventhttpclient/connectionpool.py in get_socket(self)
    164         except gevent.queue.Empty:
    165             try:
--> 166                 return self._create_socket()
    167             except:
    168                 self._semaphore.release()

~/anaconda3/envs/merlin/lib/python3.7/site-packages/geventhttpclient/connectionpool.py in _create_socket(self)
    100             or set tcp/socket options
    101         """
--> 102         sock_infos = self._resolve()
    103         first_error = None
    104         for sock_info in sock_infos:

~/anaconda3/envs/merlin/lib/python3.7/site-packages/geventhttpclient/connectionpool.py in _resolve(self)
     74         info = gevent.socket.getaddrinfo(self._connection_host,
     75                                          self._connection_port,
---> 76                                          family, 0, gevent.socket.SOL_TCP)
     77         # family, socktype, proto, canonname, sockaddr = info[0]
     78         return info

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/_socketcommon.py in getaddrinfo(host, port, family, type, proto, flags)
    245         # Our lower-level resolvers, including the thread and blocking, which use _socket,
    246         # function simply with integers.
--> 247         addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
    248         result = [
    249             (_intenum_converter(af, AddressFamily),

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/resolver/thread.py in getaddrinfo(self, *args, **kwargs)
     61 
     62     def getaddrinfo(self, *args, **kwargs):
---> 63         return self.pool.apply(_socket.getaddrinfo, args, kwargs)
     64 
     65     def gethostbyaddr(self, *args, **kwargs):

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/pool.py in apply(self, func, args, kwds)
    159         if self._apply_immediately():
    160             return func(*args, **kwds)
--> 161         return self.spawn(func, *args, **kwds).get()
    162 
    163     def __map(self, func, iterable):

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/_gevent_cevent.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cevent.AsyncResult.get()

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/_gevent_cevent.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cevent.AsyncResult.get()

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/_gevent_cevent.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cevent.AsyncResult.get()

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/_gevent_cevent.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cevent.AsyncResult._raise_exception()

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/_compat.py in reraise(t, value, tb)
     63     def reraise(t, value, tb=None): # pylint:disable=unused-argument
     64         if value.__traceback__ is not tb and tb is not None:
---> 65             raise value.with_traceback(tb)
     66         raise value
     67     def exc_clear():

~/anaconda3/envs/merlin/lib/python3.7/site-packages/gevent/threadpool.py in __run_task()
    165         self._before_run_task(func, args, kwargs, thread_result)
    166         try:
--> 167             thread_result.set(func(*args, **kwargs))
    168         except: # pylint:disable=bare-except
    169             thread_result.handle_error((self, func), self._exc_info())

gaierror: [Errno -2] Name or service not known

"

**Comment by benfred** [comment]
Can you verify that the tritonserver process is running on your local machine - and that it started up successfully?

**Comment by ng-fukgin** [comment]
> Can you verify that the tritonserver process is running on your local machine - and that it started up successfully?

Thanks,it is useful for me
