### ISSUE TITLE
[FEA] Dockerfile working for NVTabular >=0.7.1 and Rapids 21.10

### ISSUE THREAD

**Issue by esnvidia** [NVIDIA-Merlin/Merlin#72]
The current dockerfile only installs NVTabular and cuDF, but this limits available end-use cases, such as cuML, cuGraph and so on.

pseudocode for a clean Dockerfile:

```
FROM rapidsai/rapidsai:21.10-cuda11.2-runtime-ubuntu20.04-py3.8

RUN apt-get update && pip install nvtabular
```

Note, no requirement for HugeCTR, or Triton.

Aha! Link: https://nvaiinfa.aha.io/features/MERLIN-837

**Comment by exzine** [comment]
will there be a merlin come with cuml been released anytime soon? I have tried to build cuml from source inside the merlin container, not very successful.

**Comment by esnvidia** [comment]
@exzine - @bschifferer or @albert17 may know the answer to this. I made the feature request for that purpose

**Comment by nv-alaiacano** [comment]
Closing because we have a _rapidly_ (get it?) different docker setup than back in 2021. Feel free to open a new ticket if this issue persists with the current Merlin containers in NGC.
