### ISSUE TITLE
[QST]Fail to docker build from dockerfile.ctr, pull access denied for nvcr.io/nvstaging/merlin/merlin-base

### ISSUE THREAD

**Issue by heroes999** [NVIDIA-Merlin/Merlin#782]
# ❓ Questions & Help
I've suceeded to login in nvcr.io, but still cannot pull from nvcr.io/nvstaging/merlin/merlin-base.
Is this NGC still available now?

cmd: 
cd docker && docker build --pull -t hugectr:devel -f ./dockerfile.ctr --build-arg RELEASE=false --build-arg RMM_VER=vnightly --build-arg CUDF_VER=vnightly --build-arg NVTAB_VER=vnightly --build-arg HUGECTR_DEV_MODE=true --no-cache  .

**Comment by nv-alaiacano** [comment]
We don't make the `merlin-base` container (or anything in `nvstaging`) available publicly, though it is possible to build it yourself.

You can build the `dockerfile.merlin` container first, which produces the base image. Then you can build the `dockerfile.ctr` container from that.

I'll close this issue but if you have any problems feel free to re-open.

**Comment by heroes999** [comment]
Thanks for reply. I will try to build from dockerfile.merlin first
