### ISSUE TITLE
Align on metrics to be tracked for performance regression using ASV

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#797]
- [ ] Align on which notebooks to be included

**Comment by bschifferer** [comment]
@radekosmulski shared an update on it in https://nvidia.slack.com/archives/CVBDJUPEZ/p1679617586380369 and waited for input there.

Summary: As we changed our focus to session-based, we should prfioritize performance regression on session-based models.

We want to track:
- Runtime NVTabular for session-based workflow
- Runtime Training session-based model 
- Performance metrics for session-based model

We will use https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/transformers-next-item-prediction.ipynb as the starting point.

@radekosmulski provided a WIP PR: https://github.com/NVIDIA-Merlin/models/pulls

**Comment by bschifferer** [comment]
@viswa-nvidia I close the ticket, as we aligned on the metrics and we are implementing it now.
