### ISSUE TITLE
[QST] Adding Google Cloud SDK to Merlin-Pytorch:22.12

### ISSUE THREAD

**Issue by ldane** [NVIDIA-Merlin/Merlin#810]
# ❓ Questions & Help
Incompatible python libraries while building Vertex AI container.

## Details

We're following [this](https://github.com/GoogleCloudPlatform/nvidia-merlin-on-vertex-ai/blob/main/env-config/Dockerfile) repository for creating our development environment for Merlin-Pytorch:22.12. While creating the container image, we are getting these messages about missing dependencies or incompatible versions.

Is this expected result?

fastai 2.7.10 requires spacy<4, which is not installed.
fastai 2.7.10 requires torchvision>=0.8.2, which is not installed.
dask-cudf 22.8.0a0+304.g6ca81bbc78.dirty requires cupy-cuda118<12,>=9.5.0, which is not installed.
cudf 22.8.0a0+304.g6ca81bbc78.dirty requires cupy-cuda118<12,>=9.5.0, which is not installed.
merlin-core 0.10.0 requires fsspec==2022.5.0, but you have fsspec 2023.1.0 which is incompatible.
jupyterlab-server 2.17.0 requires jsonschema>=4.17.3, but you have jsonschema 3.2.0 which is incompatible.
jupyter-events 0.5.0 requires jsonschema[format-nongpl]>=4.3.0, but you have jsonschema 3.2.0 which is incompatible.
grpcio-channelz 1.51.1 requires protobuf>=4.21.6, but you have protobuf 3.20.3 which is incompatible.
distributed 2022.7.1 requires tornado<6.2,>=6.0.3, but you have tornado 6.2 which is incompatible.
cudf 22.8.0a0+304.g6ca81bbc78.dirty requires cuda-python<11.7.1,>=11.5, but you have cuda-python 11.8.1 which is incompatible.

**Comment by rnyak** [comment]
@ldane these warnings should be fine. are you able to do the following? 

```
import nvtabular
import cudf, dask_cudf
import torch
```

**Comment by ldane** [comment]
@rnyak Yes, I can import them. I wanted to have this messages visible in case they are related to the issue in this [ticket](https://github.com/NVIDIA-Merlin/NVTabular/issues/1764)
