### ISSUE TITLE
Capture shapes everywhere

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#823]

**Comment by viswa-nvidia** [comment]
@rnyak , please link your PR

**Comment by viswa-nvidia** [comment]
@gabrielspmoreira , please link your PR

**Comment by rnyak** [comment]
> @rnyak , please link your PR

This is the PR in TF4Rec repo: https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/646

**Comment by karlhigley** [comment]
Closing as completed
