### ISSUE TITLE
Model schemas - Make sure all libraries output a model schema (Implicit, LightFM, XGBoost don't output schemas)

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#825]
- [x] XGBoost: Done.
- [x] LightFM: https://github.com/NVIDIA-Merlin/models/pull/1002
- [x] Implicit: https://github.com/NVIDIA-Merlin/models/pull/1014

**Comment by edknv** [comment]
It looks like XGBoost already outputs schemas: https://github.com/NVIDIA-Merlin/models/blob/95f48f61f5381ff583f9c062b3dad672bd271847/merlin/models/xgb/__init__.py#L259-L264
