### ISSUE TITLE
[DOC]Can't find the /Merlin/examples/Building-and-deploying-multi-stage-RecSys/ directory after logging in to JupyterLab

### ISSUE THREAD

**Issue by andy-zt** [NVIDIA-Merlin/Merlin#863]
### Location of incorrect documentation

https://github.com/NVIDIA-Merlin/Merlin/blob/main/examples/README.md#running-the-example-notebooks
### Describe the problems or issues found in the documentation

When I follow "Running the Example Notebooks" steps, I can't find the /Merlin/examples directory after logging in to JupyterLab.

**Comment by mikemckiernan** [comment]
Hello @andy-zt. Very sorry to hear that you are experiencing trouble with running the example notebooks.

I have one suggestion: Before you run the `jupyter-lab --allow-root --ip='0.0.0.0'` that the documentation describes, please run `cd /`.  I think that change will ensure that Jupyter starts and provides access to the `/Merlin/examples` directory.

Please reply back to let us know if that resolves the issue or not.  If it does not resolve the issue, can you let us know which container you ran?

**Comment by andy-zt** [comment]
Yes that works. Thank you!

**Comment by mikemckiernan** [comment]
Ah, good!  Though, still very sorry for the trouble you experienced at first.  Keep using Merlin!
