### ISSUE TITLE
Create release notes

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#87]

**Comment by viswa-nvidia** [comment]
@karlhigley  
@gabrielspmoreira 
Please take a look

**Comment by gabrielspmoreira** [comment]
@viswa-nvidia @benfred Looking at the commits on Transformers4Rec after the last tagged version [v0.1.3](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/v0.1.3) (released by Dec 7, 2021), it seems we only had CI add and no new feature implemented.
