### ISSUE TITLE
Report additional metrics to asvdb from integration tests

### ISSUE THREAD

**Issue by jperez999** [NVIDIA-Merlin/Merlin#896]
For the example notebooks in NVTabular that are run as integration tests:

- [ ] The metrics for asvdb that should be captured:
  - [x] Training Time
  - [x] Max AUC (where possible)
  - [ ] validation loss (otherwise)
  - [x] Container Sizes
- [x] must be human readable
- [x] must be simple to understand

Source for the list of metrics: https://docs.google.com/document/d/19wktqCbcR8II0TLMIFckwbCuPTLawLxvKmbmHUnqYtU/edit

**Comment by karlhigley** [comment]
@bschifferer I think this has been superseded by newer issues?
