### ISSUE TITLE
Merlin inference container size too big

### ISSUE THREAD

**Issue by sohn21c** [NVIDIA-Merlin/Merlin#90]
Merlin inference container size, when built per https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/dockerfile.tri, is ~20GB which is big where some cloud services require container size to be limited under 10 or 15GB. A potential resolution could be to create inference containers for different framework using tf2, pyt triton base image instead of triton-py3 that contains all of backends i.e.  Tensorflow, PyTorch, TensorRT, ONNX and OpenVINO.

**Comment by kmcmearty** [comment]
@sohn21c Which cloud provider did you try this on? 
Looks like Azure is 15 GB like you mentioned.

**Comment by sohn21c** [comment]
@kmcmearty GCP

**Comment by rnyak** [comment]
@albert17 @jperez999  for viz.

**Comment by albert17** [comment]
@kmcmearty @sohn21c Working on fixing this. Created a PR
