### ISSUE TITLE
Review API documentation for PyT serving support for T4R models

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#904]

**Comment by bbozkaya** [comment]
Reviewed [API documentation](https://nvidia-merlin.github.io/Transformers4Rec/main/api/modules.html) (generated by docstrings in code) for Transformers4Rec/transformers4rec codebase. Details are available here: https://docs.google.com/document/d/1GzM1q9Pc6amecRspbWKG0PSXbU-fCy13hSOC6UMnWWU/edit

Will review API documentation for merlin_standard_lib package next.
