### ISSUE TITLE
NVTabular saving index+embedding tables as a numpy array file

### ISSUE THREAD

**Issue by EvenOldridge** [NVIDIA-Merlin/Merlin#971]
Customer has a Pretrained embedding table
 - Table with uuid + embeddings
 - uuid runs through categorify using an existing fit
 - save out as numpy array file

Missing functionality is the ability to save as a np array file

**Comment by oliverholworthy** [comment]
https://github.com/NVIDIA-Merlin/core/pull/337 Added functionality to the `Dataset` to export as npy file
