### ISSUE TITLE
Enable re-use of a fitted Categorify operator in another workflow

### ISSUE THREAD

**Issue by EvenOldridge** [NVIDIA-Merlin/Merlin#972]
In order to support pretrained embeddings we need to be able to use categorify from another workflow

This could be solved by subgraphs and is our long term solution.

Categorify fit creates a unique values file for its own internal use which doesn't contain the reserved values.  It also produces a categorify metadata file that includes counts, buckets, etc.

We need to use those files to transform the uuid column in an embedding table in order to ensure it matches the categorified column within the dataset.

**Comment by oliverholworthy** [comment]
Subgraph operator added in https://github.com/NVIDIA-Merlin/core/pull/334

**Comment by karlhigley** [comment]
There's also an example of how to do this in the tests added by https://github.com/NVIDIA-Merlin/NVTabular/pull/1827
